### PR TITLE
Fix comment clearing VIP bug

### LINKED ISSUE #72: Comment command clears VIP state
Slight interaction I overlooked

### PR DESCRIPTION
**Pull request by 1st2GetThisName**
Fixes #72

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/CommentCommand.java [hunk 1]
```diff
@@ -57,7 +57,7 @@ public CommandResult execute(Model model) throws CommandException {
         Person personToEdit = lastShownList.get(index.getZeroBased());
         Person editedPerson = new Person(
                 personToEdit.getName(), personToEdit.getPhone(), personToEdit.getEmail(),
-                personToEdit.getAddress(), comment, personToEdit.getTags());
+                personToEdit.getAddress(), comment, personToEdit.getTags(), personToEdit.isVip());
```
Comment (muller317) [inline src/main/java/seedu/address/logic/commands/CommentCommand.java:60]: May you cover this line by test?
